### ISSUE TITLE
bottom two LEDs not working (resolved)

### ISSUE THREAD

**Issue by jasonblewis** [PancakeLegend/Simon#1]
Hi,

This isn't really an issue but just wanted to document it in case it helps the next person. After building this with my 8yo we found the bottom two LEDs didn't work.

After I stared at the schematic for long enough I realised the jumper has to be close for normal operation and not open as I had left it. Once I closed the jumper, all LEDs worked as expected.

thanks for putting together this awesome kit.

**Comment by jasonblewis** [comment]
Closing as I am putting it here for future reference.

**Comment by PancakeLegend** [comment]
Hey Jason. I'm really glad you enjoyed making the kit! The [part about the jumper](https://github.com/PancakeLegend/Simon/wiki/Assembly-Guide#jumper) is included in the assembly guide. I think there may be too many words in that section to account for more advanced use cases. This may have buried the key step to put the jumper connector on the pins. I'm sorry that it took you for a loop, but thankful that you got through it. I hope you have fun playing with it now :)

**Comment by jasonblewis** [comment]
thanks @PancakeLegend. I think we missed that section in our excitement to get playing. May I contact you out of band to discuss sourcing more kits?

**Comment by PancakeLegend** [comment]
> 

You should join our Discord server, I can speak to you there. There's an invite link on the CCHS website: https://www.hackmelbourne.org/
